name: Terraform CI/CD

on:
  pull_request:
    branches:
      - dev
      - prod
  workflow_dispatch:

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, prod]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Set Azure Environment Variables
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=63b88364-e9a8-466d-aa04-570dc7d1d0f6" >> $GITHUB_ENV

      - name: Terraform Init
        working-directory: envs/${{ matrix.env }}
        run: terraform init

      - name: Terraform Plan
        working-directory: envs/${{ matrix.env }}
        run: terraform plan -out=tfplan

      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: envs/${{ matrix.env }}/tfplan

  terraform-apply:
    name: Terraform Apply (Requires Approval)
    runs-on: ubuntu-latest
    needs: terraform-plan
    strategy:
      matrix:
        env: [dev, prod]
    environment: ${{ matrix.env }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Set Azure Environment Variables
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=63b88364-e9a8-466d-aa04-570dc7d1d0f6" >> $GITHUB_ENV

      - name: Download tfplan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: envs/${{ matrix.env }}

      - name: Terraform Init
        working-directory: envs/${{ matrix.env }}
        run: terraform init

      - name: Terraform Apply
        working-directory: envs/${{ matrix.env }}
        run: terraform apply -auto-approve tfplann